version: "3.9"

services: 
    api:
        build: .
        container_name: api
        ports: 
            - "80:80"
        command: uvicorn api.entry:app --host 0.0.0.0 --port 80 --reload
        volumes: 
            - .:/app
        env_file: .env